
[package]
authors = ["João Pedro Miranda C. Hluchan <berrytern@gmail.com>"]
edition = "2024"
name    = "amqp_rs"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Link to your local core crate!
amqp-rs-core = { path = "../../core" }

# Node-specific dependencies
amqp-client-rust = { version = "=0.0.8", features = [
  "tls",
  "zstd",
  "lz4_flex",
  "flate2",
] }
napi = { version = "3.0.0", features = ["napi4", "async", "tokio_rt"] }
napi-derive = "3.0.0"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }


[build-dependencies]
napi-build = "2"
